openapi: 3.0.0
info:
  title: GetResponse APIv3 Products
  version: 3.2026-07-28T07:58:55+00:00
  description: The Products operations of the GetResponse APIv3, split by tag from the provider-published
    OpenAPI at https://apireference.getresponse.com/open-api.json
  contact:
    name: API Support - DevZone
    url: https://app.getresponse.com/feedback.html?devzone=yes
    email: getresponse-devzone@cs.getresponse.com
servers:
- url: https://api.getresponse.com/v3
  description: GetResponse
- url: https://api3.getresponse360.com/v3
  description: GetResponse MAX US
- url: https://api3.getresponse360.pl/v3
  description: GetResponse MAX PL
tags:
- name: Products
  description: Products API documentation
paths:
  /shops/{shopId}/products:
    get:
      tags:
      - Products
      summary: Get a product list.
      description: "\nSending a **GET** request to this URL returns a collection of product resources\
        \ that belong to the given shop.\n\nYou can narrow down the list of resources by passing proper\
        \ query parameters (the list of which you can find below in the request params section). You can\
        \ basically search by:\n * name\n * vendor\n * category\n * categoryId\n * externalId\n * variantName\n\
        \ * metaFieldNames\n * metaFieldValues\n * createdOn\n\nThe `metaFieldNames` and `metaFieldValues`\
        \ fields can be a list of values separated by a comma [,].\n You can filter the resource using\
        \ criteria specified as `query[*]`. You can provide multiple criteria, to use AND logic. You can\
        \ sort the resource using parameters specified as `sort[*]`. You can specify multiple fields to\
        \ sort by."
      operationId: getProductList
      parameters:
      - name: query[name]
        in: query
        description: Search products by name
        required: false
        schema:
          type: string
      - name: query[vendor]
        in: query
        description: Search products by vendor
        required: false
        schema:
          type: string
      - name: query[category]
        in: query
        description: Search products by category name
        required: false
        schema:
          type: string
      - name: query[categoryId]
        in: query
        description: Search products by category ID
        required: false
        schema:
          type: string
      - name: query[externalId]
        in: query
        description: Search products by external ID
        required: false
        schema:
          type: string
      - name: query[variantName]
        in: query
        description: Search products by product variant name
        required: false
        schema:
          type: string
      - name: query[metaFieldNames]
        in: query
        description: Search products by meta field name (the list of names must be separated by a comma
          [,])
        required: false
        schema:
          type: string
      - name: query[metaFieldValues]
        in: query
        description: Search products by meta field value (the list of values must be separated by a comma
          [,])
        required: false
        schema:
          type: string
      - name: query[createdOn][from]
        in: query
        description: Search products created from this date
        required: false
        schema:
          $ref: '#/components/schemas/DateOrDateTime'
      - name: query[createdOn][to]
        in: query
        description: Search products created to this date
        required: false
        schema:
          $ref: '#/components/schemas/DateOrDateTime'
      - name: sort[name]
        in: query
        description: Sort by name
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[createdOn]
        in: query
        description: Sort by date
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - $ref: '#/components/parameters/Fields'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/Page'
      responses:
        '200':
          $ref: '#/components/responses/ProductList'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
    parameters:
    - $ref: '#/components/parameters/shopId'
    post:
      tags:
      - Products
      summary: Create product
      description: '

        Sending a **POST** request to this URL will create a new product resource.


        In order to create a new product, you need to send the product resource in the body of the request
        (remember that you need to serialize the body into a JSON string)


        You don''t need a separate endpoint for each element (e.g. variant, category, meta-field). You
        can create them all with this method.


        Please note that categories aren''t required, but if a product has at least one category, then
        one of those categories must be marked as default.

        This can be set by field `isDefault`. If  none of the elements contains isDefault=true, then the
        system picks the first one from the collection by default.


        '
      operationId: createProduct
      requestBody:
        $ref: '#/components/requestBodies/NewProduct'
      responses:
        '201':
          $ref: '#/components/responses/ProductDetails'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
  /shops/{shopId}/products/{productId}:
    get:
      tags:
      - Products
      summary: Get a single product by ID
      description: '

        This method returns product according to the given `productId` in the context of a given `shopId`.


        '
      operationId: getProductById
      parameters:
      - $ref: '#/components/parameters/Fields'
      responses:
        '200':
          $ref: '#/components/responses/ProductDetails'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
    parameters:
    - $ref: '#/components/parameters/shopId'
    - $ref: '#/components/parameters/productId'
    post:
      tags:
      - Products
      summary: Update product
      description: "\nUpdate the properties of a shop's product. You should only send those fields that\
        \ need to be changed. The remaining properties will stay the same.\nHowever, when updating variants,\
        \ categories, and meta fields, you need to send entire collections. Individual fields can't be\
        \ updated.\nIf you want to update particular fields, you can do so using their specific endpoints,\
        \ i.e.:\n\n * categories - `POST /v3/shops/{shopId}/categories/{categoryId}`\n * variants - POST\
        \ `/v3/shops/{shopId}/products/{productId}/variants/{variantId}`\n * metaFields - `POST /v3/shops/{shopId}/meta-fields/{metaFieldId}`\n\
        \n\n"
      operationId: updateProduct
      requestBody:
        $ref: '#/components/requestBodies/UpdateProduct'
      responses:
        '200':
          $ref: '#/components/responses/ProductDetails'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
    delete:
      tags:
      - Products
      summary: Delete product
      description: ''
      operationId: deleteProduct
      responses:
        '204':
          description: Delete product
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/RateLimitLimit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/RateLimitRemaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/RateLimitReset'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
  /shops/{shopId}/products/{productId}/categories:
    post:
      tags:
      - Products
      summary: Upsert product categories
      description: '

        This method makes it possible to assign product categories, and to set a default product category.
        This method doesn''t remove or unassign product categories. It returns a list of product categories.


        Please note that if you assign only one category to a given product, that category is marked as
        default. If you try to remove the default mark, your change won''t be executed.


        '
      operationId: upsertProductCategories
      requestBody:
        $ref: '#/components/requestBodies/UpsertProductCategory'
      responses:
        '200':
          $ref: '#/components/responses/SimpleProductCategoryList'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
      x-type: upsert
    parameters:
    - $ref: '#/components/parameters/shopId'
    - $ref: '#/components/parameters/productId'
  /shops/{shopId}/products/{productId}/meta-fields:
    post:
      tags:
      - Products
      summary: Upsert product meta fields
      description: '

        This method makes it possible to assign meta fields. It doesn''t remove or unassign meta fields.
        It returns a list of product meta fields.


        '
      operationId: upsertMetaFields
      requestBody:
        $ref: '#/components/requestBodies/UpsertMetaField'
      responses:
        '200':
          $ref: '#/components/responses/MetaFieldList'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
      x-type: upsert
    parameters:
    - $ref: '#/components/parameters/shopId'
    - $ref: '#/components/parameters/productId'
components:
  headers:
    CurrentPage:
      description: The current page number
      schema:
        type: integer
        format: int32
    RateLimitLimit:
      description: The total number of requests available per time frame
      schema:
        type: integer
        format: int32
    RateLimitRemaining:
      description: The number of requests left in the current time frame
      schema:
        type: integer
        format: int32
    RateLimitReset:
      description: Seconds left in the current time frame, e.g. "432 seconds"
      schema:
        type: string
    TotalCount:
      description: The total number of resources found for the specified conditions
      schema:
        type: integer
        format: int32
    TotalPages:
      description: The total number of pages
      schema:
        type: integer
        format: int32
  parameters:
    Fields:
      name: fields
      in: query
      description: List of fields that should be returned. Id is always returned. Fields should be separated
        by comma
      required: false
      schema:
        type: string
    Page:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 1
    PerPage:
      name: perPage
      in: query
      description: Requested number of results per page
      required: false
      schema:
        type: integer
        format: int32
        default: 100
        maximum: 1000
        minimum: 1
    productId:
      name: productId
      in: path
      description: The product ID
      required: true
      schema:
        type: string
      example: 9I
    shopId:
      name: shopId
      in: path
      description: The shop ID
      required: true
      schema:
        type: string
      example: pf3
  requestBodies:
    NewProduct:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewProduct'
    UpdateProduct:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateProduct'
    UpsertMetaField:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpsertMetaField'
    UpsertProductCategory:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpsertProductCategory'
  responses:
    MetaFieldList:
      description: The list of meta fields
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
        CurrentPage:
          $ref: '#/components/headers/CurrentPage'
        TotalPages:
          $ref: '#/components/headers/TotalPages'
        TotalCount:
          $ref: '#/components/headers/TotalCount'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/MetaField'
    ProductDetails:
      description: The product details
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    ProductList:
      description: The list of products
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
        CurrentPage:
          $ref: '#/components/headers/CurrentPage'
        TotalPages:
          $ref: '#/components/headers/TotalPages'
        TotalCount:
          $ref: '#/components/headers/TotalCount'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
    SimpleProductCategoryList:
      description: The list of product categories
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BaseCategory'
  schemas:
    BaseCategory:
      properties:
        categoryId:
          description: The category ID
          type: string
          readOnly: true
          example: atQ
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/shops/pf3/categories/atQ
        name:
          description: The name of the category
          type: string
          maxLength: 64
          minLength: 2
          example: Headwear
        parentId:
          description: The parent category ID
          type: string
          maxLength: 64
          minLength: 2
          example: amh
        isDefault:
          description: This is a default category
          type: boolean
          example: true
        url:
          description: The external URL to the category
          type: string
          format: uri
          maxLength: 2048
          example: https://somedomain.com/category/446
        externalId:
          description: The external ID is the identifying string or number of the category given by another
            software
          type: string
          maxLength: 255
          example: ext3343
      type: object
    BaseMetaField:
      properties:
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/shops/pf3/meta-fields/NoF
        metaFieldId:
          description: The meta field ID
          type: string
          readOnly: true
          example: NoF
        name:
          description: The meta field name
          type: string
          maxLength: 63
          minLength: 3
          example: Shoe size
        value:
          description: The meta field value
          type: string
          maxLength: 65000
          minLength: 0
          example: '11'
        valueType:
          description: The value type enumerable
          type: string
          enum:
          - string
          - integer
          example: integer
        description:
          description: The meta field description
          type: string
          maxLength: 255
          minLength: 0
          example: Description of this meta field
      type: object
    BaseProductVariant:
      properties:
        variantId:
          description: The product ID
          type: string
          readOnly: true
          example: VTB
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/shops/pf3/products/9I/variants/VTB
        name:
          description: The product name
          type: string
          maxLength: 255
          minLength: 1
          example: Red Monster Cap
        url:
          description: The external URL to the product variant
          type: string
          format: uri
          maxLength: 2048
          example: https://somedomain.com/products-variants/986
        sku:
          description: The stock-keeping unit of a variant. Must be unique within the product
          type: string
          maxLength: 255
          minLength: 2
          example: SKU-1254-56-457-5689
        price:
          description: The price
          type: number
          format: double
          example: 20
        priceTax:
          description: The price including tax
          type: number
          format: double
          example: 27.5
        previousPrice:
          description: The price before the change
          type: number
          format: double
          example: 25
          nullable: true
        previousPriceTax:
          description: The price before the change including tax
          type: number
          format: double
          example: 33.6
          nullable: true
        quantity:
          description: The quantity of variant items
          type: integer
          format: int64
          default: 1
        position:
          description: The position of a variant
          type: integer
          format: int64
          example: 1
        barcode:
          description: The barcode of a variant
          type: string
          maxLength: 255
          minLength: 2
          example: '12455687'
        externalId:
          description: The external ID is the identifying string or number of the variant given by another
            software
          type: string
          maxLength: 255
          example: ext1456
        description:
          description: The description of a variant
          type: string
          maxLength: 1000
          minLength: 2
          example: Red Cap with GetResponse Monster print
        images:
          type: array
          items:
            $ref: '#/components/schemas/NewProductVariantImage'
        metaFields:
          type: array
          items:
            $ref: '#/components/schemas/NewMetaField'
        taxes:
          type: array
          items:
            $ref: '#/components/schemas/NewTax'
      type: object
    BaseTax:
      properties:
        taxId:
          description: The tax ID
          type: string
          readOnly: true
          example: Sk
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/shops/pf3/taxes/Sk
        name:
          description: The tax name
          type: string
          maxLength: 255
          minLength: 2
          example: VAT
        rate:
          description: The rate value
          type: number
          format: double
          maximum: 99.9
          minimum: 0
          example: 23
      type: object
    CreateAndUpdate:
      properties:
        createdOn:
          description: The creation date
          type: string
          format: date-time
          readOnly: true
        updatedOn:
          description: The date of the last update
          type: string
          format: date-time
          readOnly: true
      type: object
    DateOrDateTime:
      oneOf:
      - type: string
        format: date
        example: '2018-04-15'
      - type: string
        format: date-time
        example: 2018-01-15T13:30:42+0000
    ErrorResponse:
      required:
      - httpStatus
      - code
      - codeDescription
      - message
      - moreInfo
      - context
      - uuid
      properties:
        httpStatus:
          description: HTTP response code
          type: integer
          format: int32
        code:
          description: API error code
          type: integer
          format: int32
        codeDescription:
          description: API error code description
          type: string
        message:
          description: Error message
          type: string
        moreInfo:
          description: URL to error description in the API Docs
          type: string
        context:
          type: object
        uuid:
          description: UUID of the error response
          type: string
      type: object
    MetaField:
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseMetaField'
      - $ref: '#/components/schemas/CreateAndUpdate'
    NewMetaField:
      required:
      - name
      - value
      - valueType
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseMetaField'
    NewProduct:
      required:
      - name
      - variants
      type: object
      allOf:
      - $ref: '#/components/schemas/Product'
    NewProductCategory:
      required:
      - name
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseCategory'
    NewProductVariant:
      required:
      - name
      - price
      - priceTax
      - sku
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseProductVariant'
    NewProductVariantImage:
      required:
      - src
      - position
      properties:
        imageId:
          description: The image ID
          type: string
          readOnly: true
          example: hY
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/shops/pf3/images/hY
        src:
          description: The source URL of an image
          type: string
          format: uri
          example: http://somedomain.com/images/src/img58db7ec64bab9.png
        position:
          description: The position of an image
          type: integer
          format: int32
          example: '1'
      type: object
    NewTax:
      required:
      - name
      - rate
      type: object
      allOf:
      - $ref: '#/components/schemas/BaseTax'
    Product:
      type: object
      allOf:
      - properties:
          productId:
            description: The product ID
            type: string
            readOnly: true
            example: 9I
          href:
            description: Direct hyperlink to a resource
            type: string
            format: uri
            readOnly: true
            example: https://api.getresponse.com/v3/shops/pf3/products/9I
          name:
            description: The product name
            type: string
            maxLength: 255
            minLength: 2
            example: Monster Cap
          type:
            description: The product type
            type: string
            maxLength: 64
            minLength: 2
            example: Headwear
          url:
            description: The external URL for the product
            type: string
            format: uri
            maxLength: 2048
            example: https://somedomain.com/products/456
          vendor:
            description: The product vendor
            type: string
            maxLength: 64
            minLength: 2
            example: GetResponse
          externalId:
            description: The external ID is the identifying string or number of the product given by another
              software
            type: string
            maxLength: 255
            example: '123456'
          categories:
            type: array
            items:
              $ref: '#/components/schemas/NewProductCategory'
          variants:
            type: array
            items:
              $ref: '#/components/schemas/NewProductVariant'
          metaFields:
            type: array
            items:
              $ref: '#/components/schemas/NewMetaField'
      - $ref: '#/components/schemas/CreateAndUpdate'
    SortOrderEnum:
      type: string
      enum:
      - ASC
      - DESC
    UpdateProduct:
      type: object
      allOf:
      - $ref: '#/components/schemas/Product'
    UpsertMetaField:
      description: This method assigns metafields. It doesn't unassign or delete them.
      required:
      - metaFields
      properties:
        metaFields:
          type: array
          items:
            $ref: '#/components/schemas/UpsertSingleMetaField'
      type: object
    UpsertProductCategory:
      description: This method makes it possible to assign product categories, and to set a default product
        category. It doesn't remove or unassign product categories.
      required:
      - categories
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/UpsertSingleProductCategory'
      type: object
    UpsertSingleMetaField:
      required:
      - metaFieldId
      properties:
        metaFieldId:
          description: MetaField ID
          type: string
          example: NoF
      type: object
    UpsertSingleProductCategory:
      required:
      - categoryId
      properties:
        categoryId:
          description: The category ID
          type: string
          example: atQ
        isDefault:
          description: This is a default category
          type: boolean
          example: true
      type: object
  securitySchemes:
    api-key:
      type: apiKey
      description: Header value must be prefixed with api-key
      name: X-Auth-Token
      in: header
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://app.getresponse.com/oauth2_authorize.html
          scopes:
            all: all data access
        authorizationCode:
          authorizationUrl: https://app.getresponse.com/oauth2_authorize.html
          tokenUrl: https://api.getresponse.com/v3/token
          scopes:
            all: all data access
        clientCredentials:
          tokenUrl: https://api.getresponse.com/v3/token
          scopes:
            all: all data access
