openapi: 3.2.0
info:
  title: GetResponse APIv3 A/B tests - subject API
  version: 3.2026-07-28T07:58:55+00:00
  description: The A/B tests - subject operations of the GetResponse APIv3, split by tag from the provider-published OpenAPI at https://apireference.getresponse.com/open-api.json
  contact:
    name: API Support - DevZone
    url: https://app.getresponse.com/feedback.html?devzone=yes
    email: getresponse-devzone@cs.getresponse.com
servers:
- url: https://api.getresponse.com/v3
  description: GetResponse
- url: https://api3.getresponse360.com/v3
  description: GetResponse MAX US
- url: https://api3.getresponse360.pl/v3
  description: GetResponse MAX PL
tags:
- name: A/B tests - subject
  description: A/B tests - subject API documentation
paths:
  /ab-tests/subject/{abTestId}/winner:
    parameters:
    - $ref: '#/components/parameters/abTestId'
    post:
      tags:
      - A/B tests - subject
      summary: Choose A/B test winner
      operationId: postAbtestsSubjectByIdWinner
      requestBody:
        $ref: '#/components/requestBodies/ChooseWinnerAbtestsSubject'
      responses:
        '204':
          description: Choose A/B test winner
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/RateLimitLimit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/RateLimitRemaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/RateLimitReset'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
  /ab-tests/subject/{abTestId}:
    parameters:
    - $ref: '#/components/parameters/abTestId'
    get:
      tags:
      - A/B tests - subject
      summary: Get a single A/B test by ID
      operationId: getAbTestSubjectById
      parameters:
      - $ref: '#/components/parameters/Fields'
      responses:
        '200':
          $ref: '#/components/responses/AbtestsSubjectGetDetails'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
  /ab-tests/{abTestId}/cancel:
    parameters:
    - $ref: '#/components/parameters/abTestId'
    post:
      tags:
      - A/B tests - subject
      summary: Cancel A/B test
      description: This method allows you to schedule the cancellation of an A/B test. Cancelling an A/B test is an asynchronous operation.
      operationId: cancelAbTest
      responses:
        '202':
          description: A/B test cancellation scheduled
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/RateLimitLimit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/RateLimitRemaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/RateLimitReset'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 409
                    code: 1008
                    codeDescription: There is another resource with the same value of unique property
                    message: Property value is already taken
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1008
                    context:
                      value: test-value
                    uuid: b89a0d53-67f6-4269-b207-223b42b6bfbd
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
      x-no-body: true
  /ab-tests/{abTestId}:
    parameters:
    - $ref: '#/components/parameters/abTestId'
    delete:
      tags:
      - A/B tests - subject
      summary: Delete A/B test
      description: 'This method allows you to delete an A/B test. Deletion is only permitted when the test is in one of the following states: `draft`, `cancelled`, `finished`, or `completed`.'
      operationId: deleteAbTest
      responses:
        '204':
          description: A/B test deleted successfully
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/RateLimitLimit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/RateLimitRemaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/RateLimitReset'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
  /ab-tests/subject:
    get:
      tags:
      - A/B tests - subject
      summary: The list of A/B tests
      description: You can filter the resource using criteria specified as `query[*]`. You can provide multiple criteria, to use AND logic. You can sort the resource using parameters specified as `sort[*]`. You can specify multiple fields to sort by.
      operationId: GetAbTestSubjectList
      parameters:
      - name: query[name]
        in: query
        description: Search A/B tests by name
        required: false
        schema:
          type: string
      - name: query[stage]
        in: query
        description: Search A/B tests by stage
        required: false
        schema:
          type: string
          enum:
          - preparing
          - testing
          - finished
          - sending-winner
          - cancelled
          - draft
          - completed
      - name: query[abTestId]
        in: query
        description: Search A/B tests by ID. You can search for multiple A/B tests using comma-separated values, for example, `pgIH, CNXF`
        required: false
        schema:
          type: string
      - name: query[campaignId]
        in: query
        description: Search A/B tests by list ID. You can search for multiple A/B tests using comma-separated list IDs, for example, `pgIH, CNXF`
        required: false
        schema:
          type: string
      - name: sort[name]
        in: query
        description: Sort by name
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[stage]
        in: query
        description: Sort by stage
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[sendOn]
        in: query
        description: Sort by send date
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[totalDelivered]
        in: query
        description: Sort by total delivered
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - $ref: '#/components/parameters/Fields'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/Page'
      responses:
        '200':
          $ref: '#/components/responses/AbtestsSubjectGetList'
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
    post:
      tags:
      - A/B tests - subject
      summary: Create a new A/B test
      operationId: createSubjectAbTest
      requestBody:
        $ref: '#/components/requestBodies/NewAbtestsSubject'
      responses:
        '201':
          $ref: '#/components/responses/AbtestsSubjectGetDetails'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
components:
  schemas:
    SortOrderEnum:
      type: string
      enum:
      - ASC
      - DESC
    CampaignReference:
      required:
      - campaignId
      properties:
        campaignId:
          description: Campaign ID
          type: string
          example: C
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/campaigns/C
        name:
          description: The campaign name
          type:
          - string
          - 'null'
          readOnly: true
          example: Promo campaign
      type: object
    MessageSendSettingSelectedCampaigns:
      description: A one-element array containing the Campaign ID to filter subscribers. Any additional elements in the array will be ignored.
      type: array
      items:
        type: string
        example: C
    AbtestsSubjectStatistics:
      properties:
        delivered:
          description: The total number of delivered messages
          type: integer
          example: 10
        openRate:
          description: Percentage of messages that were opened
          type: number
          format: double
          example: 20.52
        clickRate:
          description: Percentage of messages links that were clicked
          type: number
          format: double
          example: 5.12
      type: object
    AbtestsSubjectListItem:
      type: object
      allOf:
      - properties:
          status:
            description: Newsletter status
            type: string
            enum:
            - active
            - inactive
            - deleted
            readOnly: true
          stage:
            description: A/B test stage
            type: string
            enum:
            - preparing
            - testing
            - finished
            - sending_winner
            - cancelled
            - draft
            - completed
            readOnly: true
          deliverySettings:
            description: The A/B test delivery settings
            properties:
              sendOn:
                description: Date the newsletter was sent on
                properties:
                  date:
                    description: Date the newsletter was sent on
                    type:
                    - string
                    - 'null'
                    format: date-time
                    example: 2015-07-25T20:05:10+0000
                  timeZone:
                    description: Time zone in which the newsletter was sent
                    properties:
                      timeZoneId:
                        description: ID of the time zone the newsletter was sent in
                        type: integer
                      timeZoneName:
                        description: Name of the time zone the newsletter was sent in
                        type:
                        - integer
                        - 'null'
                      timeZoneOffset:
                        description: Time zone, or UTC, offset for when the newsletter was sent
                        type:
                        - integer
                        - 'null'
                    type: object
                type: object
              winnerMode:
                description: A/B test winner selection mode
                type: string
                enum:
                - automatic
                - manual
              winningCriteria:
                description: A/B test winning criteria
                type: string
                enum:
                - open
                - click
              samplingPercentage:
                description: Size of the test (sampling) group, expressed as a percentage. Setting 100% with the `automatic` winnerMode will result in splitting the entire package between the variants, with no additional messages sent to the winner.
                type: integer
                format: int32
                maximum: 100
                minimum: 1
              samplingTime:
                description: A/B testing phase duration. The time after which the remaining recipients will be sent the winning message
                type:
                - string
                - 'null'
                format: ISO-8601 duration
                example: '86400'
            type: object
          flags:
            type: array
            items:
              description: Tracking options enabled for the newsletter
              type: string
              enum:
              - clicktrack
              - subscription_reminder
              - openrate
              - google_analytics
              - manual_list
              - custom_footer
              - ecommerce_tracking
              readOnly: true
          createdOn:
            description: Date the A/B test was created on
            type:
            - string
            - 'null'
            format: date-time
            example: 2015-07-25T20:05:10+0000
          updatedOn:
            description: Date A/B test was updated on
            type:
            - string
            - 'null'
            format: date-time
            example: 2015-07-25T20:05:10+0000
          href:
            description: Direct hyperlink to a resource
            type: string
            format: uri
            readOnly: true
            example: https://api.getresponse.com/v3/ab-tests/subject/A3r
        type: object
      - $ref: '#/components/schemas/AbtestsSubject'
    FromFieldReference:
      required:
      - fromFieldId
      properties:
        fromFieldId:
          description: The 'From' address ID
          type: string
          example: V
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/from-fields/V
      type: object
    NewAbtestsSubject:
      type: object
      allOf:
      - required:
        - name
        - campaign
        - fromField
        properties:
          abTestId:
            description: A/B test ID
            type: string
            readOnly: true
            example: A3r
          name:
            description: A/B test name
            type: string
            maxLength: 100
            minLength: 1
            example: A/B test
          campaign:
            $ref: '#/components/schemas/CampaignReference'
          fromField:
            $ref: '#/components/schemas/FromFieldReference'
          replyTo:
            $ref: '#/components/schemas/FromFieldReference'
        type: object
      - required:
        - deliverySettings
        - variants
        - sendSettings
        - content
        properties:
          deliverySettings:
            description: The A/B test delivery settings
            required:
            - samplingTime
            - winningCriteria
            - winnerMode
            - sendOn
            properties:
              sendOn:
                description: Date the newsletter was sent on
                required:
                - sendingType
                properties:
                  sendingType:
                    description: Newsletter send type. Please note that date and timezone are not allowed with the 'now' option
                    type: string
                    enum:
                    - now
                    - scheduled
                    example: scheduled
                  date:
                    description: Date the newsletter was sent on
                    type:
                    - string
                    - 'null'
                    format: Y-m-d H:i:s
                    example: '2015-07-25T20:05:10'
                  timeZone:
                    description: Time zone in which the newsletter was sent
                    required:
                    - timeZoneId
                    properties:
                      timeZoneId:
                        description: ID of the time zone the newsletter was sent in
                        type: integer
                        example: 285
                    type: object
                type: object
              winnerMode:
                description: A/B test winner selection mode
                type: string
                enum:
                - automatic
                - manual
              winningCriteria:
                description: A/B test winning criteria
                type: string
                enum:
                - open
                - click
              samplingPercentage:
                description: Size of the test (sampling) group, expressed as a percentage. Setting 100% with the `automatic` winnerMode will result in splitting the entire package between the variants, with no additional messages sent to the winner.
                type: integer
                format: int32
                maximum: 100
                minimum: 1
              samplingTime:
                description: A/B testing phase duration. The time after which the remaining recipients will be sent the winning message
                type:
                - string
                - 'null'
                format: ISO-8601 duration
                example: P0Y0M0DT5H30M0S
            type: object
          flags:
            type: array
            items:
              description: Tracking options enabled for the newsletter
              type: string
              enum:
              - clicktrack
              - google_analytics
              - ecommerce_tracking
          variants:
            description: Message variants. Please note, the number of subject variants should be between 2 and 5
            type: array
            items:
              description: Variant's subject
              type: string
              maximum: 150
              minimum: 1
              example: variant
          sendSettings:
            description: The send settings for the A/B test
            properties:
              selectedCampaigns:
                $ref: '#/components/schemas/MessageSendSettingSelectedCampaigns'
              selectedSegments:
                $ref: '#/components/schemas/MessageSendSettingSelectedSegments'
              selectedSupressions:
                $ref: '#/components/schemas/MessageSendSettingSelectedSuppressions'
              excludedCampaigns:
                $ref: '#/components/schemas/MessageSendSettingExcludedCampaigns'
              excludedSegments:
                $ref: '#/components/schemas/MessageSendSettingExcludedSegments'
            type: object
          content:
            $ref: '#/components/schemas/MessageContent'
        type: object
    MessageContent:
      description: The message content.
      properties:
        html:
          description: The message content in HTML
          type: string
          maxLength: 524288
          example: <h1>test 12</h1><p>Some test <a href="http://example.com">http://example.com</a></p>
        plain:
          description: The plain text equivalent of the message content
          type: string
          maxLength: 524288
          example: test 12 Some test
      type: object
    MessageSendSettingSelectedSuppressions:
      description: The list of suppression IDs to exclude subscribers.
      type: array
      items:
        type: string
        example: Ss
    AbtestsSubject:
      properties:
        abTestId:
          description: A/B test ID
          type: string
          readOnly: true
          example: A3r
        name:
          description: A/B test name
          type: string
          maxLength: 100
          minLength: 1
          example: A/B test
        campaign:
          description: List linked to A/B test
          properties:
            campaignId:
              description: Campaign ID
              type: string
              example: C
            href:
              description: Direct hyperlink to a resource
              type: string
              format: uri
              readOnly: true
              example: https://api.getresponse.com/v3/campaigns/C
          type: object
        fromField:
          description: Newsletter's From" address"
          properties:
            fromFieldId:
              description: The 'From' address ID
              type: string
              example: V
            href:
              description: Direct hyperlink to a resource
              type: string
              format: uri
              readOnly: true
              example: https://api.getresponse.com/v3/from-fields/V
          type: object
        replyTo:
          description: Newsletter's reply-to address
          properties:
            fromFieldId:
              description: The 'From' address ID
              type: string
              example: V
            href:
              description: Direct hyperlink to a resource
              type: string
              format: uri
              readOnly: true
              example: https://api.getresponse.com/v3/from-fields/V
          type: object
      type: object
    AbtestsSubjectDetails:
      type: object
      allOf:
      - properties:
          winnerSendingStart:
            description: Date the winning message was sent on
            type:
            - string
            - 'null'
            format: date-time
            example: 2015-07-25T20:05:10+0000
          statistics:
            description: The statistics of A/B test
            properties:
              total:
                description: Aggregated statistics for all messages (winner and variants) sent both during and after the evaluation period
                type: object
                allOf:
                - $ref: '#/components/schemas/AbtestsSubjectStatistics'
              winner:
                description: Statistics for the winner, collected both during and after the evaluation period
                type: object
                allOf:
                - $ref: '#/components/schemas/AbtestsSubjectStatistics'
            type: object
            readOnly: true
          variants:
            type: array
            items:
              properties:
                variantId:
                  description: The message variant ID. A variant identifier from https://apireference.getresponse.com/#operation/getAbtestsSubjectById.
                  type: string
                  readOnly: true
                  example: VpKJdr
                index:
                  description: Variant's index field (A, B, C...)
                  type: string
                  readOnly: true
                  example: A
                subject:
                  description: Variant's subject
                  type: string
                  maximum: 150
                  minimum: 1
                  example: variant
                isWinner:
                  description: Winning variant
                  type: boolean
                  readOnly: true
                  example: true
                statistics:
                  description: Statistics of a variant collected during evaluation period
                  type: object
                  readOnly: true
                  allOf:
                  - $ref: '#/components/schemas/AbtestsSubjectStatistics'
              type: object
          sendSettings:
            description: The send settings for the A/B test
            properties:
              selectedCampaigns:
                $ref: '#/components/schemas/MessageSendSettingSelectedCampaigns'
              selectedSegments:
                $ref: '#/components/schemas/MessageSendSettingSelectedSegments'
              selectedSupressions:
                $ref: '#/components/schemas/MessageSendSettingSelectedSuppressions'
              excludedCampaigns:
                $ref: '#/components/schemas/MessageSendSettingExcludedCampaigns'
              excludedSegments:
                $ref: '#/components/schemas/MessageSendSettingExcludedSegments'
            type: object
          editor:
            description: The message editor used for the A/B test
            type:
            - string
            - 'null'
            enum:
            - html2
            - custom
            - text
            - editor_v3
            - getresponse
            - legacy
          content:
            $ref: '#/components/schemas/MessageContent'
        type: object
      - $ref: '#/components/schemas/AbtestsSubjectListItem'
    MessageSendSettingSelectedSegments:
      description: The list of segment IDs to choose subscribers from.
      type: array
      items:
        type: string
        example: Se
    MessageSendSettingExcludedSegments:
      description: The list of segment IDs to exclude subscribers.
      type: array
      items:
        type: string
        example: eSs
    MessageSendSettingExcludedCampaigns:
      description: The list of campaign IDs to exclude subscribers.
      type: array
      items:
        type: string
        example: eC
    ErrorResponse:
      required:
      - httpStatus
      - code
      - codeDescription
      - message
      - moreInfo
      - context
      - uuid
      properties:
        httpStatus:
          description: HTTP response code
          type: integer
          format: int32
        code:
          description: API error code
          type: integer
          format: int32
        codeDescription:
          description: API error code description
          type: string
        message:
          description: Error message
          type: string
        moreInfo:
          description: URL to error description in the API Docs
          type: string
        context:
          type: object
        uuid:
          description: UUID of the error response
          type: string
      type: object
    ChooseWinnerAbtestsSubject:
      required:
      - variantId
      properties:
        variantId:
          description: The message variant ID. A variant identifier from https://apireference.getresponse.com/#operation/getAbtestsSubjectById.
          type: string
          example: VpKJdr
      type: object
  headers:
    TotalPages:
      description: The total number of pages
      schema:
        type: integer
        format: int32
    CurrentPage:
      description: The current page number
      schema:
        type: integer
        format: int32
    RateLimitRemaining:
      description: The number of requests left in the current time frame
      schema:
        type: integer
        format: int32
    TotalCount:
      description: The total number of resources found for the specified conditions
      schema:
        type: integer
        format: int32
    RateLimitLimit:
      description: The total number of requests available per time frame
      schema:
        type: integer
        format: int32
    RateLimitReset:
      description: Seconds left in the current time frame, e.g. "432 seconds"
      schema:
        type: string
  parameters:
    PerPage:
      name: perPage
      in: query
      description: Requested number of results per page
      required: false
      schema:
        type: integer
        format: int32
        default: 100
        maximum: 1000
        minimum: 1
    abTestId:
      name: abTestId
      in: path
      description: A/B test ID
      required: true
      schema:
        type: string
      example: xyz
    Page:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 1
    Fields:
      name: fields
      in: query
      description: List of fields that should be returned. Id is always returned. Fields should be separated by comma
      required: false
      schema:
        type: string
  requestBodies:
    ChooseWinnerAbtestsSubject:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChooseWinnerAbtestsSubject'
    NewAbtestsSubject:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewAbtestsSubject'
  responses:
    AbtestsSubjectGetDetails:
      description: A/B test details
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AbtestsSubjectDetails'
    AbtestsSubjectGetList:
      description: The list of A/B tests
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
        CurrentPage:
          $ref: '#/components/headers/CurrentPage'
        TotalPages:
          $ref: '#/components/headers/TotalPages'
        TotalCount:
          $ref: '#/components/headers/TotalCount'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AbtestsSubjectListItem'
  securitySchemes:
    api-key:
      type: apiKey
      description: Header value must be prefixed with api-key
      name: X-Auth-Token
      in: header
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://app.getresponse.com/oauth2_authorize.html
          scopes:
            all: all data access
        authorizationCode:
          authorizationUrl: https://app.getresponse.com/oauth2_authorize.html
          tokenUrl: https://api.getresponse.com/v3/token
          scopes:
            all: all data access
        clientCredentials:
          tokenUrl: https://api.getresponse.com/v3/token
          scopes:
            all: all data access
