openapi: 3.0.0
info:
  title: GetResponse APIv3 Legacy Landing Pages
  version: 3.2026-07-28T07:58:55+00:00
  description: The Legacy Landing Pages operations of the GetResponse APIv3, split by tag from the provider-published
    OpenAPI at https://apireference.getresponse.com/open-api.json
  contact:
    name: API Support - DevZone
    url: https://app.getresponse.com/feedback.html?devzone=yes
    email: getresponse-devzone@cs.getresponse.com
servers:
- url: https://api.getresponse.com/v3
  description: GetResponse
- url: https://api3.getresponse360.com/v3
  description: GetResponse MAX US
- url: https://api3.getresponse360.pl/v3
  description: GetResponse MAX PL
tags:
- name: Legacy Landing Pages
  description: Legacy Landing Pages description
paths:
  /landing-pages/{landingPageId}:
    get:
      tags:
      - Legacy Landing Pages
      summary: Get single landing page by ID
      operationId: getLandingPageById
      parameters:
      - $ref: '#/components/parameters/Fields'
      responses:
        '200':
          $ref: '#/components/responses/LandingPageDetails'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 404
                    code: 1013
                    codeDescription: The requested resource was not found
                    message: Resource not found
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1013
                    context:
                      contactId: pVyRW
                    uuid: 87b90a96-5ee5-4ca4-8180-ac00adcf62c7
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
    parameters:
    - $ref: '#/components/parameters/landingPageId'
  /landing-pages:
    get:
      tags:
      - Legacy Landing Pages
      summary: Get a list of landing pages
      description: You can filter the resource using criteria specified as `query[*]`. You can provide
        multiple criteria, to use AND logic. You can sort the resource using parameters specified as `sort[*]`.
        You can specify multiple fields to sort by.
      operationId: getLandingPageList
      parameters:
      - name: query[domain]
        in: query
        description: Search landing pages by domain
        required: false
        schema:
          type: string
      - name: query[status]
        in: query
        description: Search landing pages by status
        required: false
        schema:
          $ref: '#/components/schemas/StatusEnum'
      - name: query[subdomain]
        in: query
        description: Search landing pages by subdomain
        required: false
        schema:
          type: string
      - name: query[metaTitle]
        in: query
        description: Search landing pages by metaTitle field
        required: false
        schema:
          type: string
      - name: query[userDomain]
        in: query
        description: Search landing pages by user provided domain
        required: false
        schema:
          type: string
      - name: query[campaignId]
        in: query
        description: Search landing pages by ID of the assigned campaign. Campaign ID must be encoded!
          You can get the campaign list with encoded IDs by calling the `/v3/campaigns` endpoint. You
          can search by multiple comma separated values eg. `o5lx,34er`.
        required: false
        schema:
          type: string
      - name: query[createdOn][from]
        in: query
        description: Show landing pages created from this date
        required: false
        schema:
          $ref: '#/components/schemas/DateOrDateTime'
      - name: query[createdOn][to]
        in: query
        description: Show landing pages created to this date
        required: false
        schema:
          $ref: '#/components/schemas/DateOrDateTime'
      - name: sort[createdOn]
        in: query
        description: Sort by date
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[domain]
        in: query
        description: Sort by domain
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[campaignId]
        in: query
        description: Sort by campaign
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - name: sort[metaTitle]
        in: query
        description: Sort by metaTitle
        required: false
        schema:
          $ref: '#/components/schemas/SortOrderEnum'
      - $ref: '#/components/parameters/Fields'
      - $ref: '#/components/parameters/PerPage'
      - $ref: '#/components/parameters/Page'
      responses:
        '200':
          $ref: '#/components/responses/LandingPageList'
        '400':
          description: Request validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 400
                    code: 1000
                    codeDescription: General error of validation process, more details should be in context
                      section
                    message: Validation error, see context section for more information
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1000
                    context:
                      validationType: searchFilter[query]
                      fieldName: name
                      originalName: lorem-ipsum
                      errorDescription: Not allowed search field
                    uuid: 77dabfd1-1fa7-4f9f-8d3f-487b4403e3aa
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 401
                    code: 1014
                    codeDescription: Problem during authentication process, check headers!
                    message: Unable to authenticate request. Check credentials or authentication method
                      details
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1014
                    context:
                      authenticationType: auth_token
                    uuid: 62417847-4f12-4c25-9b3a-0b619a187efe
        '429':
          description: The throttling limit has been reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example:
                  value:
                    httpStatus: 429
                    code: 1015
                    codeDescription: Too many request to API, quota reached, please wait till next quota
                      window
                    message: You have reached your requests limit for this time window, please wait...
                    moreInfo: https://apidocs.getresponse.com/en/v3/errors/1015
                    context:
                      currentLimit: 30000
                      timeToReset: 100 seconds
                    uuid: 510c6726-7f65-46b7-a798-ca403133924f
      security:
      - api-key: []
      - oauth2:
        - all
components:
  headers:
    CurrentPage:
      description: The current page number
      schema:
        type: integer
        format: int32
    RateLimitLimit:
      description: The total number of requests available per time frame
      schema:
        type: integer
        format: int32
    RateLimitRemaining:
      description: The number of requests left in the current time frame
      schema:
        type: integer
        format: int32
    RateLimitReset:
      description: Seconds left in the current time frame, e.g. "432 seconds"
      schema:
        type: string
    TotalCount:
      description: The total number of resources found for the specified conditions
      schema:
        type: integer
        format: int32
    TotalPages:
      description: The total number of pages
      schema:
        type: integer
        format: int32
  parameters:
    Fields:
      name: fields
      in: query
      description: List of fields that should be returned. Id is always returned. Fields should be separated
        by comma
      required: false
      schema:
        type: string
    Page:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 1
    PerPage:
      name: perPage
      in: query
      description: Requested number of results per page
      required: false
      schema:
        type: integer
        format: int32
        default: 100
        maximum: 1000
        minimum: 1
    landingPageId:
      name: landingPageId
      in: path
      description: The landing page ID.
      required: true
      schema:
        type: string
      example: avYn
  responses:
    LandingPageDetails:
      description: The landing pages details.
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/LandingPage'
    LandingPageList:
      description: The list of landing pages.
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/RateLimitLimit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/RateLimitRemaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/RateLimitReset'
        CurrentPage:
          $ref: '#/components/headers/CurrentPage'
        TotalPages:
          $ref: '#/components/headers/TotalPages'
        TotalCount:
          $ref: '#/components/headers/TotalCount'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BaseLandingPage'
  schemas:
    BaseLandingPage:
      properties:
        landingPageId:
          description: The landing page ID
          type: string
          example: avYn
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          example: https://api.getresponse.com/v3/landing-pages/avYn
        metaTitle:
          description: The landing page meta title property
          type: string
          example: Some meta title
        domain:
          description: The domain where the landing page is hosted
          type: string
          example: gr8.new
        subdomain:
          description: The subdomain where the landing page is assigned
          type: string
          example: summer-sale
        userDomain:
          description: The private domain provided by the user
          type: string
          example: ''
        userDomainPath:
          description: The private domain path provided by the user
          type: string
          example: ''
        campaign:
          description: The campaign to which the landing page is linked
          allOf:
          - $ref: '#/components/schemas/CampaignReference'
        status:
          description: The landing page status
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
        userDomainStatus:
          description: The DNS status for the user's private domain. Can be `null` if a private domain
            isn't assigned.
          type: string
          enum:
          - active
          - inactive
          - waiting
          nullable: true
        testAB:
          description: Does the landing page have AB testing (variants) enabled
          example: 'true'
          allOf:
          - $ref: '#/components/schemas/StringBooleanEnum'
        createdOn:
          description: The creation date
          type: string
          format: date-time
          readOnly: true
        updatedOn:
          description: The date of the last page update
          type: string
          format: date-time
          readOnly: true
      type: object
    CampaignReference:
      required:
      - campaignId
      properties:
        campaignId:
          description: Campaign ID
          type: string
          example: C
        href:
          description: Direct hyperlink to a resource
          type: string
          format: uri
          readOnly: true
          example: https://api.getresponse.com/v3/campaigns/C
        name:
          description: The campaign name
          type: string
          readOnly: true
          example: Promo campaign
          nullable: true
      type: object
    DateOrDateTime:
      oneOf:
      - type: string
        format: date
        example: '2018-04-15'
      - type: string
        format: date-time
        example: 2018-01-15T13:30:42+0000
    ErrorResponse:
      required:
      - httpStatus
      - code
      - codeDescription
      - message
      - moreInfo
      - context
      - uuid
      properties:
        httpStatus:
          description: HTTP response code
          type: integer
          format: int32
        code:
          description: API error code
          type: integer
          format: int32
        codeDescription:
          description: API error code description
          type: string
        message:
          description: Error message
          type: string
        moreInfo:
          description: URL to error description in the API Docs
          type: string
        context:
          type: object
        uuid:
          description: UUID of the error response
          type: string
      type: object
    LandingPage:
      type: object
      allOf:
      - properties:
          metaDescription:
            description: The landing page meta description property
            type: string
            example: Some meta description
          metaNoindex:
            description: To entirely prevent your page content from being listed in the Google web index,
              even if other sites link to it use a noindex meta tag
            type: string
            enum:
            - 'yes'
            - 'no'
          dayOfCycle:
            description: Contacts subscribed via the landing page will be added to the autoresponder cycle.
              `Null` if contacts shouldn't be added to the cycle.
            type: integer
            format: int32
            maximum: 9999
            minimum: 0
            example: 2
            nullable: true
          optin:
            description: The opt-in type (double or single)
            type: string
            enum:
            - single
            - double
          favicoUrl:
            description: The favicon URL. Can be `null` if a favicon isn't present
            type: string
            format: uri
            example: https://my-landing-page.mohahaha.com/favico.ico
            nullable: true
          thankYouPageType:
            description: What should happen after a contact subscribes
            type: string
            enum:
            - stay_on_page
            - default
            - custom_url
          thankYouPageUrl:
            description: The `thank-you` page URL. Can be empty if a custom thank-you page isn't being
              used
            type: string
            format: uri
            example: https://my-landing-page.mohahaha.com/thank_you.html
          url:
            description: The landing page URL
            type: string
            format: uri
            example: https://my-landing-page.mohahaha.com
          variants:
            type: array
            items:
              $ref: '#/components/schemas/LandingPageVariant'
      - $ref: '#/components/schemas/BaseLandingPage'
    LandingPageVariant:
      properties:
        variantId:
          description: The landing page variant ID.
          type: string
          example: PKxn
        variant:
          description: The variant index.
          type: string
          format: integer
          example: '0'
        winner:
          type: boolean
          example: true
        visitors:
          type: string
          format: integer
          example: '12'
        uniqueVisitors:
          type: string
          format: integer
          example: '2'
        subscribed:
          type: string
          format: integer
          example: '2'
      type: object
    SortOrderEnum:
      type: string
      enum:
      - ASC
      - DESC
    StatusEnum:
      type: string
      enum:
      - enabled
      - disabled
    StringBooleanEnum:
      type: string
      enum:
      - 'true'
      - 'false'
  securitySchemes:
    api-key:
      type: apiKey
      description: Header value must be prefixed with api-key
      name: X-Auth-Token
      in: header
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://app.getresponse.com/oauth2_authorize.html
          scopes:
            all: all data access
        authorizationCode:
          authorizationUrl: https://app.getresponse.com/oauth2_authorize.html
          tokenUrl: https://api.getresponse.com/v3/token
          scopes:
            all: all data access
        clientCredentials:
          tokenUrl: https://api.getresponse.com/v3/token
          scopes:
            all: all data access
